"""added relation UserProjectAssociation

Revision ID: fc9cdda5c80e
Revises: 7baa028e0180
Create Date: 2024-03-17 13:15:38.247927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9cdda5c80e'
down_revision: Union[str, None] = '7baa028e0180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'user_id')
    # ### end Alembic commands ###
